# Generated by Django 5.2.4 on 2025-08-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='sprite_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
